name: on-push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'

    - name: cache-deps
      uses: actions/cache@v1
      env:
        cache-name: cache-deps
      with:
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: install-deps
      run: clojure -R:test -R:dev -Spath
    - name: run-tests
      run: clojure -R:dev -A:test
